version: "3.7"
services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  api-guardias:
    build:
      context: .
      dockerfile: ./api-guardias/Dockerfile
    ports:
      - "5000:5000"

  esp-nodes:
    build:
      context: .
      dockerfile: ./esp-nodes/Dockerfile

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
